### ISSUE TITLE
Is this your app?

### ISSUE THREAD

**Issue by CoolCash1** [tombailey/dead-link-detection#7]
Ive been searching for old Minecraft maps for a long time now. I used  an app call [Maps For Minecraft PE](https://play.google.com/store/apps/details?id=me.tombailey.mapsforminecraftpelite) probably 6 or 7 years back and would love to redownload some of the worlds. I installed it on my phone to see that it is no longer supported by the developer, so I googled the name of the dev (Tom Bailey) and quickly found your Github account. If your not the creator of this app, dont worry about it. But if you are, please try to get back to me.

**Comment by tombailey** [comment]
Sorry for not replying earlier. I suggest you reach out to the developer you mention using their support email on the Google Play page.

I am going to close this issue because it isn't related to this project.
